# Generated by Django 4.0.4 on 2022-06-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uom',
            name='uom_code',
            field=models.CharField(default='-', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_height',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_length',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_volume',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_volume_uom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_weight',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uom',
            name='uom_width',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uom',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uom',
            name='uom_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
