# Generated by Django 4.0.4 on 2022-06-11 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting_uom', '0002_uom_uom_code_uom_uom_height_uom_uom_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_uom', models.CharField(default='-', max_length=10, unique=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_oum_user_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_oum_user_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupUomDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_to', models.FloatField(default=0)),
                ('base_qty', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_definition_base', to='setting_uom.uom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_definition_oum_user_created', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_definition', to='setting_uom.groupuom')),
                ('uom_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_definition_to', to='setting_uom.uom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_definition_oum_user_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
