# Generated by Django 4.0.4 on 2022-06-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0004_alter_uom_uom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuom',
            name='group_uom',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
