# Generated by Django 4.0.4 on 2022-06-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('setting_uom', '0005_alter_groupuom_group_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuom',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_group_merchant_id', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='groupuomdefinition',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_group_def_merchant_id', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='uom',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_merchant_id', to='merchants.merchant'),
        ),
    ]
