# Generated by Django 4.0.4 on 2022-06-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0006_groupuom_merchant_id_groupuomdefinition_merchant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuom',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='groupuomdefinition',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupuomdefinition',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='uom',
            old_name='merchant_id',
            new_name='merchant',
        ),
    ]
