# Verion of docker-compose to use 
version: "3"

services:
  db:
    image: mysql:8.0
    #platform: linux/amd64
    restart: always
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty!123
      - MYSQL_PASSWORD=Qwerty!123
      - MYSQL_USER=gawaipos
      - MYSQL_DATABASE=gawaipos
    ports:
      - '3366:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gw-network
  gawaipos:
    build:
      context: . 
    ports:
      - "8000:8000"
      
    volumes: 
      - .:/gawaipos
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=gawaipos
      - DB_USER=gawaipos
      - DB_PASS=Qwerty!123
    depends_on:
      - db
    networks:
      - gw-network
  webmicros:
    build:
      context: ./webmicros/webmicro/
    ports:
      - "8001:8000"
      
    volumes: 
      - ./webmicros/webmicro:/usr/src/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000" 
    restart: always
    depends_on:
      - db
    networks:
      - gw-network
volumes:
  db:
    driver: local
#Docker Networks
networks:
  gw-network:
    driver: bridge