# Generated by Django 4.0.4 on 2022-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_owner_hp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_owner_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
