# Generated by Django 4.0.4 on 2022-05-24 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_business', models.CharField(max_length=50)),
                ('address_business', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('wa_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='logo')),
                ('slogan', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_mcrw', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_mcrw', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
