# Generated by Django 4.0.4 on 2022-06-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.TextField(),
        ),
    ]
