# Generated by Django 4.0.4 on 2022-05-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slogan',
            field=models.CharField(max_length=150),
        ),
    ]
