# Generated by Django 4.0.4 on 2022-06-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microweb', '0002_alter_aboutus_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
