# Generated by Django 4.0.4 on 2022-06-12 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microweb', '0003_alter_aboutus_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('product_keywords', models.CharField(default='', max_length=150)),
                ('product_title', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=250)),
                ('product_view_body', models.TextField()),
                ('wa_number', models.CharField(max_length=15)),
                ('thumb_product', models.ImageField(upload_to='thumb_product')),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_mcrw_products', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_mcrw_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'microweb_product_list',
            },
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keywords',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='ProductListImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('product_images_keywords', models.CharField(default='', max_length=150)),
                ('product_images_title', models.CharField(default='', max_length=100)),
                ('product_images_body', models.TextField()),
                ('product_images', models.ImageField(upload_to='product_images')),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_mcrw_images', to=settings.AUTH_USER_MODEL)),
                ('product_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_list_images_id', to='microweb.productlist')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_mcrw_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'microweb_product_list_images',
            },
        ),
    ]
