# Generated by Django 4.0.4 on 2022-06-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('microweb', '0004_productlist_aboutus_keywords_profile_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='productlist',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='productlistimages',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
    ]
