# Generated by Django 4.0.4 on 2022-06-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microweb', '0007_remove_productlistimages_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='productlistimages',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='productlistimages',
            old_name='product_list_id',
            new_name='product_list',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='wa_number',
        ),
    ]
