# Generated by Django 4.0.4 on 2022-06-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microweb', '0008_rename_merchant_id_aboutus_merchant_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='microweb_profile',
        ),
    ]
