# Generated by Django 3.2.13 on 2022-05-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20220522_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
