# Generated by Django 4.0.4 on 2022-06-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0001_initial'),
        ('master', '0006_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting_uom.uom'),
        ),
        migrations.DeleteModel(
            name='Uom',
        ),
    ]
