# Generated by Django 4.0.4 on 2022-06-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0001_initial'),
        ('master', '0007_alter_catalog_uom_delete_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_catalog_id', to='setting_uom.uom'),
        ),
    ]
