# Generated by Django 4.0.4 on 2022-06-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_catalog_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_tipe',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=50),
        ),
    ]
