# Generated by Django 4.0.4 on 2022-06-12 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0006_groupuom_merchant_id_groupuomdefinition_merchant_id_and_more'),
        ('master', '0011_catalog_merchant_id_customer_merchant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='uom_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_group_catalog_id', to='setting_uom.groupuom'),
        ),
    ]
