# Generated by Django 4.0.4 on 2022-06-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting_uom', '0006_groupuom_merchant_id_groupuomdefinition_merchant_id_and_more'),
        ('master', '0012_catalog_uom_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='uom',
        ),
        migrations.AddField(
            model_name='catalog',
            name='uom_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_inventory', to='setting_uom.uom'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='uom_purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_purchase', to='setting_uom.uom'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='uom_purchase_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_purchase_price', to='setting_uom.uom'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='uom_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_sales', to='setting_uom.uom'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='uom_sell_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_sell_price', to='setting_uom.uom'),
        ),
    ]
