# Generated by Django 4.0.4 on 2022-06-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('master', '0013_remove_catalog_uom_catalog_uom_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='uom_group_id',
            new_name='uom_group',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.AddField(
            model_name='category',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_merchant_id', to='merchants.merchant'),
        ),
    ]
