# Generated by Django 3.2.13 on 2022-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockonhand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
