# Generated by Django 4.0.4 on 2022-06-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockonhand_merchant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockonhand',
            old_name='merchant_id',
            new_name='merchant',
        ),
    ]
