# Generated by Django 4.0.4 on 2022-06-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_brand_id_alter_vehicle_brand_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclebrandoftype',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclebrand'),
        ),
    ]
