# Generated by Django 4.0.4 on 2022-06-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('vehicles', '0004_alter_vehiclebrandoftype_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_merchant_id', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='vehicleowner',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner_merchant_id', to='merchants.merchant'),
        ),
    ]
