# Generated by Django 4.0.4 on 2022-06-11 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0006_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_num', models.CharField(max_length=50, unique=True)),
                ('trx_date', models.DateField()),
                ('voucher_code', models.CharField(max_length=15)),
                ('is_credit', models.BooleanField(default=True)),
                ('trx_due_date', models.DateField()),
                ('is_ppn', models.BooleanField(default=True)),
                ('disc_type', models.CharField(choices=[('PERCENT', 'PERCENT'), ('AMOUNT', 'AMOUNT')], default='PERCENT', max_length=50)),
                ('disc', models.FloatField(default=0)),
                ('grand_total', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_createdby', to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_customerid', to='master.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
