# Generated by Django 4.0.4 on 2022-06-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('sales', '0002_salesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_merchant_id', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='merchant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item_merchant_id', to='merchants.merchant'),
        ),
    ]
